### ISSUE TITLE
Spelling mistake in the package.json license

### ISSUE THREAD

**Issue by srujandeshpande** [srujandeshpande/DrinkWaterBot#52]
The license field in package.json should be exactly `Apache-2.0`
The hyphen was missing from #47

**Comment by iamkrish-coder** [comment]
Hi, I am a first timer and I would like to contribute to some of your open issues, I am currently getting Permission denied while I am trying to push a change to create PR. I have this change done on my local clone of your repository. Could you please help me push the changes to your review?
