### ISSUE TITLE
Add an approximate location to `water iss`

### ISSUE THREAD

**Issue by srujandeshpande** [srujandeshpande/DrinkWaterBot#85]
`water iss` returns the current lat and long of the ISS above the earth. An approximate location using any freely available online API  would be nice

![image](https://user-images.githubusercontent.com/47925600/137539323-67abdc19-c492-4ed0-b8aa-f6ecfc9182a5.png)

For example, a location like South Africa/Johannesburg/Cape Town/etc should be returned for a location like this

**Comment by Omicron02** [comment]
Could i work on this? I'll also add the same for the corresponding slash command.
