### ISSUE TITLE
Add an `im thirsty` command

### ISSUE THREAD

**Issue by srujandeshpande** [srujandeshpande/DrinkWaterBot#88]
It can follow a similar pattern as `im hungry`. The outputs can be different. (Maybe more aggressive?)

https://github.com/acmpesuecc/DrinkWaterBot/blob/a8cf8e61661967de0118e2a3f33ab881b9974d9a/src/commands/obscure.js#L12

**Comment by themsiqueira** [comment]
I can take that?

**Comment by MercheLorenzo** [comment]
Hello! I would like to work on this, could I? Thank you so much!

**Comment by ArnavKumar7** [comment]
yes you can go on :) thank you for participation

**Comment by JoyenBenitto** [comment]
hey I want to work on this

**Comment by ArnavKumar7** [comment]
Go on :) thanks for working on this
